[package]
name = "libparse"
version = "0.1.0"
authors = ["eomain"]
description = "parse a stream of tokens producing an AST"
edition = "2018"

[dependencies]
libast = { path = "../libast" }
libtoken = { path = "../libtoken" }

[dev-dependencies]
liblex = { path = "../liblex" }
